version: '3.4'

services:
  BooksAndVideosMongoDb:
    image: mongo

  BooksAndVideosMssqlDb:
    image: mcr.microsoft.com/mssql/server:2022-latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  customercommands.api:
    image: ${DOCKER_REGISTRY-}customercommandsapi
    build:
      context: .
      dockerfile: Services/CustomerCommands/CustomerCommand.API/Dockerfile

  customerquery.api:
    image: ${DOCKER_REGISTRY-}customerqueryapi
    build:
      context: .
      dockerfile: Services/CustomerQuery/CustomerQuery.API/Dockerfile