version: '3.4'

services:
  BooksAndVideosMongoDb:
    container_name: BooksAndVideosMongoDb
    restart: always
    ports:
      - "27017:27017"

  BooksAndVideosMssqlDb:
    container_name: BooksAndVideosMssqlDb
    environment:
      MSSQL_SA_PASSWORD: "ImI12345678"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  customercommands.api:
    container_name: customercommands.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:CustomerConnectionString=Server=BooksAndVideosMssqlDb;Database=BooksAndVideosDb;User Id=sa;Password=ImI12345678;Encrypt=false
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - BooksAndVideosMssqlDb
    ports:
      - "8001:80"

  customerquery.api:
    container_name: customerquery.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://BooksAndVideosMongoDb:27017"
      - EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - BooksAndVideosMongoDb
    ports:
      - "8000:80"